#!/bin/sh -e
#
# aufs on tmpfs config
# https://wiki.debian.org/sbuild#Using_aufs_on_tmpfs_with_sbuild
#
# Copied into /etc/schroot/setup.d/04tmpfs

. "$SETUP_DATA_DIR/common-data"  # $STAGE
OVERLAY=/var/lib/schroot/union/overlay

case $STAGE in
    setup-start|setup-recover) mount -t tmpfs overlay $OVERLAY ;;
    setup-stop) umount -f $OVERLAY ;;
esac
